### ISSUE TITLE
Adding local packages

### ISSUE THREAD

**Issue by jgellar** [RevolutionAnalytics/miniCRAN#68] opened 2016-04-05 05:14 UTC
I saw somewhere that miniCRAN supports adding packages from local files, and from GitHub, but I don't see a way to do it and there are some outstanding Issues that don't seem to be resolved. Can you confirm - does miniCRAN support local packages, and/or GitHub packages?

**Comment by achubaty** [comment] 2016-04-05 14:08
As far as I know, this is not in the package and is listed as an upcoming enhancement idea (#23). I have a custom function I've been using for my own purposes, which I will cleanup and contribute to the package.

**Comment by achubaty** [comment] 2016-04-05 15:31
@jgellar #58 and #59 suggest that using `file:///` to specify the repo for download may already work.

**Comment by achubaty** [comment] 2016-04-05 16:24
nevermind, I read that wrong. those two issues are about installing FROM a local repo not adding a local package to one.

**Comment by jgellar** [comment] 2016-04-05 21:43
Thanks @achubaty for looking into it. I'd love to see your custom function, if you could share.

In order to add a package, is it sufficient to just copy the source package (e.g., from my own library for an installed package) into the miniCRAN repo? I could manage the dependencies manually (just making sure that all dependencies for my local packages are also in the repo).

Or does that skip some internal step?

**Comment by jamieo-ms** [comment] 2016-06-08 17:08
You can, in theory, add custom R packages to a local repository and AzureML *should* be able to pull from there.  Two problems:
- `download.packages` doesn't do what you might expect with local repositories, so it currently doesn't work(#109).
- AzureML requires both "source" and "win.binary" versions of all packages right now(#108)

**Comment by achubaty** [comment] 2017-04-01 03:34
@jgellar see the updated issue #23 where I've added a `addLocalPackage` function in a feature branch. Feedback appreciated.

**Comment by achubaty** [comment] 2017-06-06 15:51
closing as duplicate of #23

**Closed by achubaty** 2017-06-06 15:51 UTC
Labels: duplicate
